In [1]:
import numpy as np

In [2]:
M = np.ones((2, 3))
a = np.arange(3)

In [3]:
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
a

array([0, 1, 2])

In [5]:
M = np.ones((3, 2))
a = np.arange(3)

In [6]:
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
a

array([0, 1, 2])

In [8]:
a[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [13]:
a[:,np.newaxis]

array([[0],
       [1],
       [2]])

In [16]:
np.logaddexp(M, a[:, np.newaxis])

array([[1.31326169, 1.31326169],
       [1.69314718, 1.69314718],
       [2.31326169, 2.31326169]])

In [17]:
X = np.random.random((10, 3))

In [21]:
X

array([[0.90254223, 0.04645953, 0.77560052],
       [0.19807376, 0.25799586, 0.32304112],
       [0.2602491 , 0.54899196, 0.35810299],
       [0.95248505, 0.61147162, 0.13653405],
       [0.62043048, 0.69359931, 0.29924005],
       [0.68320479, 0.46816995, 0.32423104],
       [0.13433537, 0.8202091 , 0.34114281],
       [0.28183761, 0.8899535 , 0.06496255],
       [0.1271383 , 0.9213454 , 0.95078847],
       [0.59446537, 0.3080471 , 0.92822245]])

In [41]:
X.mean(0)

array([0.47547621, 0.55662433, 0.4501866 ])

In [36]:
X-X.mean(0)

array([[ 0.42706602, -0.51016481,  0.32541392],
       [-0.27740245, -0.29862847, -0.12714548],
       [-0.21522711, -0.00763237, -0.09208362],
       [ 0.47700885,  0.05484729, -0.31365255],
       [ 0.14495428,  0.13697498, -0.15094656],
       [ 0.20772858, -0.08845438, -0.12595557],
       [-0.34114083,  0.26358477, -0.1090438 ],
       [-0.19363859,  0.33332917, -0.38522405],
       [-0.34833791,  0.36472107,  0.50060186],
       [ 0.11898916, -0.24857724,  0.47803584]])

In [46]:
(X-X.mean(0)).mean(0)

array([ 3.33066907e-17, -5.55111512e-17,  4.44089210e-17])

In [70]:
1 | 2

3

In [51]:
42 or 59

42

In [65]:
x = np.arange(10)
(x > 4) & (x < 8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [55]:
42 and 53

53

In [75]:
import numpy as np
rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [76]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [81]:
row = np.array([0, 1, 2])

In [83]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
row

array([0, 1, 2])

In [86]:
col = np.array([2, 1, 3])

In [91]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
mask

array([ True, False,  True, False])

In [90]:
row[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [88]:
mask = np.array([1, 0, 1, 0], dtype=bool)
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [93]:
X[:, 1]

array([1, 5, 9])

In [95]:
X.shape

(3, 4)

In [97]:
X.shape[0]

3

In [98]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])